---
- name: Install dependencies
  become: yes
  apt: pkg={{item}} state=installed
  with_items:
    - nodejs
    - npm



curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
npm config set prefix '/home/vagrant'
sudo apt-get install -y nodejs


export PATH=$PATH:$HOME/.npm-global/bin
